name: macOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ['16.1']  # Update to the version of Xcode you require

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Xcode ${{ matrix.xcode_version }}
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: ${{ matrix.xcode_version }}

    - name: Install dependencies (if needed)
      run: |
        # Uncomment the next line if your project uses CocoaPods
        # pod install

    - name: Build the project
      run: |
        xcodebuild -project argus-macos-egress.xcodeproj \  # Replace 'YourProject.xcodeproj' with your actual project file
                   -scheme argus-ingress-ios \  # Replace 'argus-ingress-ios' with your scheme name
                   -configuration Release \  # Use 'Debug' or 'Release' as needed
                   -sdk macosx \  # Ensures the SDK is set to macOS
                   build




    - name: Run tests
      run: |
        xcodebuild test -workspace YourProject.xcworkspace \  # Replace as needed
                       -scheme YourScheme \  # Replace with your actual scheme
                       -destination 'platform=macOS' \  # Modify if running on other platforms like iOS
                       -configuration Debug \  # or Release based on your requirements
                       -enableCodeCoverage YES

    - name: Generate code coverage report (optional)
      if: always()
      run: |
        # Process code coverage if necessary, or use other tools to report coverage
        echo "Code coverage report generated"
